### ISSUE TITLE
[Bug Report] Nginx 타임존 설정 문제

### ISSUE THREAD

**Issue by AlphaTechnic** [neo-wolley/wolley-deploy#104]
## 환경

![image](https://user-images.githubusercontent.com/58129950/155041694-57af051c-bd65-4afc-b232-b930fa7039f7.png)

- GCP setting
  - region : 오사카
  - 삭제 보호 : 설정됨
  - 부팅디스크
    - 운영체제 : ubuntu
  - 방화벽 : HTTP 트래픽
  - 고정 IP
  - port opend
    - 22, 80, 443, 8000, 8080, 8888, 9000
  - https 인증
- 도커 version 3.7
  - django-gunicorn 컨테이너 (custom image 기반)
  - nginx 1.19.5 컨테이너
  - mariadb 10.5 컨테이너
   
## 문제 상황 (기댓값 vs 실젯값)

**[기댓값]**

- nginx의 로그가 한국 시간을 기준하여 남겨지기를 기대함

**[실젯값]**

- nginx의 로그가 미국 시간을 기준하여 남겨지고 있음.

## 문제 원인 추정

- nginx가 docker의 timezone을 참조하지를 못하는 상황

## 실제 문제 원인

- nginx 컨테이너 생성 시, environment 설정

## Trial

- `docker-compose.yml`에서 `environment` 옵션을 활용

  ```yaml
  ngnix:
      image: nginx:1.19.5
      environment:
        - TZ=Asia/Seoul
      volumes:
        - /home/alpha_technic/nginx_setting/nginx.conf:/etc/nginx/nginx.conf
        - static-volume:/data/static
      networks:
        - network
      ports:
        - 80:80
  ```

=> 결과 : **성공**

  

## 해결 여부

- [x] 해결 완료
- [ ] 해결 중
